version: '3.8'

services:
  django:
    # Берем Dockerfile из ./docker/django/
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    image: thermopol_django
    container_name: thermopol_django
    # Определяем внешние тома (volume) и места, где они будут подключены внутри контейнера
    volumes:
      - thermopol_static:/thermopol/static
      - thermopol_media:/thermopol/media
    # Открываем порт 8050 внутри
    expose:
      - "8050"
    environment:
      - ALLOWED_HOSTS=thermopol.lad-academy.ru
      # - DEBUG=${DEBUG}
      # - SECRET_KEY=${SECRET_KEY}
      
      # - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      # - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
      
    # Собираем статику, делаем миграции и запускаем WSGI
    command: sh -c "python manage.py collectstatic --no-input &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      gunicorn thermopol.wsgi -b 0.0.0.0:8050 "

  

  nginx:
    restart: always
    build:
      context: ./docker/nginx/
      dockerfile: ./Dockerfile
    image: thermopol_nginx
    container_name: thermopol_nginx
    ports:
      - "3003:3003"
    volumes:
      - thermopol_static:/thermopol/static
      - thermopol_media:/thermopol/media
    depends_on:
      - django

volumes:
  thermopol_static:
  thermopol_media:
