# Generated by Django 4.2.5 on 2024-05-07 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Literature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name": "источник",
                "verbose_name_plural": "источники",
            },
        ),
        migrations.CreateModel(
            name="SubstanceClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "класс вещества",
                "verbose_name_plural": "классы веществ",
            },
        ),
        migrations.CreateModel(
            name="Substance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "substance_type",
                    models.CharField(
                        choices=[
                            ("Мономер", "Мономер"),
                            ("Полимер", "Полимер"),
                            ("Олигомер", "Олигомер"),
                            ("неизвестно", "неизвестно"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("formula", models.CharField(max_length=100)),
                (
                    "source",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "literatura",
                    models.ManyToManyField(
                        blank=True, null=True, to="myapp.literature"
                    ),
                ),
                (
                    "substance_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.substanceclass",
                    ),
                ),
            ],
            options={
                "verbose_name": "соединение",
                "verbose_name_plural": "соединения",
            },
        ),
    ]
